theme: minima
description: >- # this means to ignore newlines until "baseurl:"
      A repository for assimilating knowledge of various aspects of Sanatan Dharma
      with the aim of refining and converging on factual information and developing 
      authentic interpretations.
header_pages:
    - about.md
    - yourideas.md
minima:
    skin: dark
    


